Feat/crud users
aristeu-garcia/M.I.D.A.S pull request #2
Opened 2024-03-11 02:13 UTC by aristeu-garcia

## Criando crud de clients

![image](https://github.com/aristeu-garcia/M.I.D.A.S/assets/76592155/ba9404e0-d1d2-4575-88fd-5b8865ae6023)

### Critérios de aceite:

- Correção da estrutura do projeto
- Edição das camadas MVT de clients

2024-03-11 02:19 UTC, Tarcyo approved these changes

2024-03-14 14:20 UTC, HeithorUrquiza approved these changes
Aristeu falou, água parou kk

2024-03-19 23:32 UTC, arthurdiasdeveloper requested changes
No arquivo de migrations, notei que na query do banco de dados esta especificando que o ID é primary kay, mas não foi definido como Not Nul, isso pode ocasionar um problema caso o usuário não inseria os dados. A menos que haja alguma excessão informando o erro que pode ser ocasionado. Observação: no modelo Client, o campo id não precisa ser definido explicitamente, pois o Django cria automaticamente um campo id de autoincremento para modelos se nenhum campo de chave primária for especificado.


No arquivo views.py, a função index está dentro da função ClientView, o que não parece correto. Além disso, a função index retorna uma resposta de renderização de modelo, o que não é comum em API REST. Pode ser necessário revisar a estrutura do projeto e a lógica das views, caso essa ideia não faça sentido, explique...

2024-03-19 23:36 UTC, arthurdiasdeveloper commented
Depois da uma olhadinha na classe de modelagem, eu não lembro ao certo, mas o Django já cria o ID automaticamente. Não há necessidade de especificar. Caso eu esteja errado, desconsidere este comentário em especifico!

2024-03-19 23:39 UTC, arthurdiasdeveloper commented
Primary key (escrevi errado) rsrs

2024-03-20 10:49 UTC, HeithorUrquiza commented
Eu sei que eu aprovei a PR, mas revisando a fundo aqui devo rever minha ação. 

- Como o Arthur disse o Django gera automaticamente o id para cada model, então não é necessário especificar 

- O Django também já conta com um model para usuários, logo não acho necessário a criação de um a parte, visto que mesmo os campos declarados são os mesmo, senão parecidos, com os que já vem por padrão.

- Nas models também ouve uma confusão na criação de referência ou foreing key. Você referenciou as proprias models, então não está havendo relacionamento entre as tabelas na prática

- Na viewset você criou funções para o CRUD de clientes, todavia não é necessário porque essas operações já estâo configuradas dentro da classe herdada ModelViewSet. E para a criação de um filter, seria interessante uma view que apenas retornace uma lista com os dados que foram solicitados

- Por fim, a respeito da organização das pastas, eu pensei em criar algumas separadas para cada model. Por exemplo, uma para Clients, uma para noticias etc de forma que ficasse mais fácil gerenciar as rotas e demais funcionaidades ao invés de deixar tudo aglomerado no 'app_midas'

2024-03-23 16:27 UTC, arthurdiasdeveloper approved these changes
Estou aprovando o PR porque o Heitor irá corrigir os arquivos na máquina dele.

2024-03-23 16:28 UTC, merged